const FASTPATH_INPUT_EVENT_SCANCODE = 0x0;
const FASTPATH_INPUT_EVENT_MOUSE = 0x1;
const FASTPATH_INPUT_EVENT_MOUSEX = 0x2;
const FASTPATH_INPUT_EVENT_SYNC = 0x3;
const FASTPATH_INPUT_EVENT_UNICODE = 0x4;
const FASTPATH_INPUT_EVENT_QOE_TIMESTAMP = 0x6;
